### ISSUE TITLE
Running ERC error - No such file or directory: 'recordmydesktop'

### ISSUE THREAD

**Issue by bzgec** [INTI-CMNB/KiBot#134]
When running ERC I get the following error:
```
- Running the ERC
DEBUG:Executing: ['eeschema_do', '-r', '-vvv', 'run_erc', '-o', '/home/bzgec/Projects/homeAutomation/display_mqtt/HW/Outputs/v0.1/esp32_display-erc.txt', '-f', '/home/bzgec/Projects/homeAutomation/display_mqtt/HW/Outputs/v0.1/kibot_errors.filter', '/home/bzgec/Projects/homeAutomation/display_mqtt/HW/Board/v0.1/esp32_display.kicad_sch', '/home/bzgec/Projects/homeAutomation/display_mqtt/HW/Board/v0.1/../../Outputs/v0.1'] (kibot - kiplot.py:168)
DEBUG:Command line: eeschema_do -r -vvv run_erc -o /home/bzgec/Projects/homeAutomation/display_mqtt/HW/Outputs/v0.1/esp32_display-erc.txt -f /home/bzgec/Projects/homeAutomation/display_mqtt/HW/Outputs/v0.1/kibot_errors.filter /home/bzgec/Projects/homeAutomation/display_mqtt/HW/Board/v0.1/esp32_display.kicad_sch /home/bzgec/Projects/homeAutomation/display_mqtt/HW/Board/v0.1/../../Outputs/v0.1 (kibot - kiplot.py:170)
DEBUG:Failed with error 1, retrying ... (kibot - kiplot.py:177)
DEBUG:Output from command:
> DEBUG:Detected KiCad v6.0.0 (6.0.0 6000000) (eeschema_do - misc.py:138)
> DEBUG:Config path /home/bzgec/.config/kicad/6.0 (eeschema_do - misc.py:153)
> DEBUG:KiCad environment: {'MYLIB': '/home/bzgec/Projects/homeAutomation/display_mqtt/HW/kicadLib'} (eeschema_do - misc.py:233)
> DEBUG:Loading filter errors (eeschema_do.kiauto.file_util - file_util.py:73)
> INFO:Loaded 4 error filters from `/home/bzgec/Projects/homeAutomation/display_mqtt/HW/Outputs/v0.1/kibot_errors.filter`
> DEBUG:English locale: en_US.utf8 (eeschema_do - misc.py:271)
> DEBUG:Eeschema config: /home/bzgec/.config/kicad/6.0/eeschema.json (eeschema_do.kiauto.file_util - file_util.py:181)
> DEBUG:Moving current config to /home/bzgec/.config/kicad/6.0/eeschema.json.pre_script (eeschema_do.kiauto.file_util - file_util.py:188)
> DEBUG:Creating an eeschema config (eeschema_do - eeschema_do:439)
> DEBUG:Selecting plot format pdf (4) (eeschema_do - eeschema_do:442)
> DEBUG:{"plot": {"format": 4, "color": true, "frame_reference": true, "color_theme": "_builtin_default"}, "system": {"first_run_shown": true, "never_show_rescue_dialog": true}, "appearance": {"show_sexpr_file_convert_warning": false}, "window": {"size_x": 1366, "size_y": 960}} (eeschema_do - eeschema_do:456)
> DEBUG:KiCad common config: /home/bzgec/.config/kicad/6.0/kicad_common.json (eeschema_do.kiauto.file_util - file_util.py:181)
> DEBUG:Moving current config to /home/bzgec/.config/kicad/6.0/kicad_common.json.pre_script (eeschema_do.kiauto.file_util - file_util.py:188)
> DEBUG:Creating a KiCad common config (eeschema_do - eeschema_do:477)
> DEBUG:{"environment": {"show_warning_dialog": false, "vars": {"MYLIB": "/home/bzgec/Projects/homeAutomation/display_mqtt/HW/kicadLib"}}, "system": {"editor_name": "/bin/cat"}} (eeschema_do - eeschema_do:488)
> DEBUG:User hotkeys config: /home/bzgec/.config/kicad/6.0/user.hotkeys (eeschema_do.kiauto.file_util - file_util.py:181)
> DEBUG:Moving current config to /home/bzgec/.config/kicad/6.0/user.hotkeys.pre_script (eeschema_do.kiauto.file_util - file_util.py:188)
> DEBUG:Creating a user hotkeys config (eeschema_do.kiauto.file_util - file_util.py:196)
> DEBUG:Redirecting eeschema output to eeschema*.log (eeschema_do.kiauto.file_util - file_util.py:284)
> DEBUG:Waiting for virtual X server ... (eeschema_do.kiauto.ui_automation - ui_automation.py:87)
> DEBUG:Current DISPLAY is :1453112317 (eeschema_do.kiauto.ui_automation - ui_automation.py:89)
> DEBUG:Checking using ['setxkbmap', '-query'] (eeschema_do.kiauto.ui_automation - ui_automation.py:100)
> DEBUG:Redirecting setxkbmap output to setxkbmap*.log (eeschema_do.kiauto.file_util - file_util.py:284)
> DEBUG:['setxkbmap', '-query'] returned 0 (eeschema_do.kiauto.ui_automation - ui_automation.py:106)
> DEBUG:Waiting 0.5 seconds before using the X server (eeschema_do.kiauto.ui_automation - ui_automation.py:107)
> DEBUG:Recording session with: ['recordmydesktop', '--overwrite', '--no-sound', '--no-frame', '--on-the-fly-encoding', '-o', '/home/bzgec/Projects/homeAutomation/display_mqtt/HW/Outputs/v0.1/run_erc_eeschema_screencast.ogv'] (eeschema_do.kiauto.ui_automation - ui_automation.py:162)
> DEBUG:Redirecting recordmydesktop output to recordmydesktop*.log (eeschema_do.kiauto.file_util - file_util.py:284)
> Traceback (most recent call last):
>   File "/usr/bin/eeschema_do", line 594, in <module>
>     with recorded_xvfb(cfg, retry):
>   File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
>     return next(self.gen)
>   File "/usr/lib/python3.10/site-packages/kiauto/ui_automation.py", line 206, in recorded_xvfb
>     with start_record(cfg.record, cfg.video_dir, cfg.video_name):
>   File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
>     return next(self.gen)
>   File "/usr/lib/python3.10/site-packages/kiauto/ui_automation.py", line 164, in start_record
>     with PopenContext(cmd, stdout=flog_out, stderr=flog_err, close_fds=True, start_new_session=True) as screencast_proc:
>   File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
>     raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: 'recordmydesktop'
> DEBUG:Restoring old eeschema config (eeschema_do.kiauto.file_util - file_util.py:165)
> DEBUG:Restoring old KiCad common config (eeschema_do.kiauto.file_util - file_util.py:165)
> DEBUG:Restoring old user hotkeys config (eeschema_do.kiauto.file_util - file_util.py:165)
> DEBUG:Checking if /home/bzgec/Projects/homeAutomation/display_mqtt/HW/Board/v0.1/esp32_display.kicad_pro was modified (eeschema_do.kiauto.file_util - file_util.py:257)
> DEBUG:Checking if /home/bzgec/Projects/homeAutomation/display_mqtt/HW/Board/v0.1/esp32_display.kicad_prl was modified (eeschema_do.kiauto.file_util - file_util.py:257)
>  (kibot - kiplot.py:181)
ERROR:ERC returned 1 (kibot.pre_erc - pre_erc.py:65)
```
The `eeschema_*.log`, `recordmydesktop_*.log` and `setxkbmap_err.log` are empty. Only `setxkbmap_out.log` is filled with:
```
rules:      evdev
model:      pc105
layout:     us
```

You can try to recreate the problem from my [repo](https://github.com/bzgec/esp32_display).
Running Arch Linux with `kibot-git` package.

KiCad version: 6.0.0
KiBot version: 0.11.0
Python version: 3.10.1

**Comment by set-soft** [comment]
As the error says you don't have the `recordmydesktop` tools (mentioned in KiAuto documentation). Options:

- Install it
- Reduce the debug level to avoid recording the session
