### ISSUE TITLE
Boardview error

### ISSUE THREAD

**Issue by frfa** [INTI-CMNB/KiBot#143]
While generating a boardview with default options for a KiCad 6.0.1 file:
```python
Traceback (most recent call last):
  File "/usr/bin/kibot", line 16, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/kibot/__main__.py", line 351, in main
    generate_outputs(outputs, args.target, args.invert_sel, args.skip_pre)
  File "/usr/local/lib/python3.8/dist-packages/kibot/kiplot.py", line 362, in generate_outputs
    run_output(out)
  File "/usr/local/lib/python3.8/dist-packages/kibot/kiplot.py", line 338, in run_output
    out.run(get_output_dir(out_dir))
  File "/usr/local/lib/python3.8/dist-packages/kibot/out_base.py", line 88, in run
    self.options.run(self.expand_filename(output_dir, self.options.output))
  File "/usr/local/lib/python3.8/dist-packages/kibot/out_boardview.py", line 161, in run
    convert(GS.board, f)
  File "/usr/local/lib/python3.8/dist-packages/kibot/out_boardview.py", line 51, in convert
    pcb.GetBoardPolygonOutlines(outlines, "")
  File "/usr/lib/python3/dist-packages/pcbnew.py", line 20659, in GetBoardPolygonOutlines
    return _pcbnew.BOARD_GetBoardPolygonOutlines(self, aOutlines, aErrorHandler)
NotImplementedError: Wrong number or type of arguments for overloaded function 'BOARD_GetBoardPolygonOutlines'.
  Possible C/C++ prototypes are:
    BOARD::GetBoardPolygonOutlines(SHAPE_POLY_SET &,OUTLINE_ERROR_HANDLER *)
    BOARD::GetBoardPolygonOutlines(SHAPE_POLY_SET &)
```

Config:
```yaml
kibot:
  version: 1

preflight:
  run_drc: false


outputs:

  - name: boardview
    comment: Board view (see boardview.org)
    type: boardview
```

KiBot called as `kibot -v -c aaa.kibot.yaml -b aaa.kicad_pcb boardview`, latest version from GitHub.
```shell
$ kibot -V
KiBot 0.11.0 - Copyright 2018-2021, Salvador E. Tropea/INTI/John Beard - License: GPL v3+
```

Looks like the `GetBoardPolygonOutlines()` method is called with wrong number of args in pcbnew.py?

**Comment by frfa** [comment]
Yes I'm on the master branch:
```
$ git status
On branch master
Your branch is up to date with 'origin/master'.
```
I couldn't find a dedicated development branch though.

**Comment by frfa** [comment]
Seems to work now, once I removed the `pip` install.
I had a mixture of `pip install` and the Debian package with `dpkg -i` - obviously those do not play well together.
Sorry for the confusion.
