### ISSUE TITLE
Excellon output not working

### ISSUE THREAD

**Issue by sethkaz** [INTI-CMNB/KiBot#25]
The excellon output is not working for me.  I have found that if I generate the files using KiCAD's GUI, the kibot script works without complaint.  However, if I run it after that it throws this exception.  

From the looks of it, it's either that the excellon portion doesn't instruct pcbnew to generate that initial file OR there is a mismatch in file namings with and without "-drill". 

Setup:
KiCad 5.1.7-a382d34a8~87~ubuntu20.04.1
KiBot 0.7.0 installed using .deb file
Python 3.8
OS: Ubuntu 20.04.1

Yaml:
```
  - name: Drill file
    comment: "Create the drill file"
    type: excellon
    dir: outputs/gerbers

```
Command Line Output:

(Executed kibot without any prep to show error is present)
```
seth@seth-[comp-name]-5:~/dev/[project name]$ kibot -e [project name].sch
Using config file: outputs.kibot.yaml
- 'Create the schematic PDF' (Schematic_PDF) [pdf_sch_print]
- 'A PDF of the PCB layers with them all combined.' (PCB_PDF_combined_layers) [pdf_pcb_print]
- 'Generate the gerber files for fab. Per PCBWay' (Gerber files) [gerber]
- 'Create the drill file' (Drill file) [excellon]
Traceback (most recent call last):
  File "/usr/bin/kibot", line 16, in <module>
    main()
  File "/home/seth/.local/lib/python3.8/site-packages/kibot/__main__.py", line 319, in main
    generate_outputs(outputs, args.target, args.invert_sel, args.skip_pre)
  File "/home/seth/.local/lib/python3.8/site-packages/kibot/kiplot.py", line 262, in generate_outputs
    out.run(get_output_dir(out.dir), board)
  File "/home/seth/.local/lib/python3.8/site-packages/kibot/out_base.py", line 55, in run
    self.options.run(output_dir, board)
  File "/home/seth/.local/lib/python3.8/site-packages/kibot/out_any_drill.py", line 106, in run
    os.rename(k_file, file)
FileNotFoundError: [Errno 2] No such file or directory: '/home/seth/dev/[project name]/outputs/gerbers/[project name]-PTH.drl' -> '/home/seth/dev/[project name]/outputs/gerbers/[project name]-PTH_drill.drl'
```
(Generated drill files from KiCAD GUI.  kibot executes without error)
```
seth@seth-[comp name]-5:~/dev/[project name]$ kibot -e [project name].sch
Using config file: outputs.kibot.yaml
- 'Create the schematic PDF' (Schematic_PDF) [pdf_sch_print]
- 'A PDF of the PCB layers with them all combined.' (PCB_PDF_combined_layers) [pdf_pcb_print]
- 'Generate the gerber files for fab. Per PCBWay' (Gerber files) [gerber]
- 'Create the drill file' (Drill file) [excellon]
- 'File for Assembly house.  Also called Centroid file' (Pick n place file) [position]
- 'Generate a step file to import into Solidworks' (Step file) [step]
- 'Generate a BOM for the SMT Assembly House' (BOM_SMT) [bom]
- 'Generate the BOM to be fed into PartsBox.' (BOM for Partsbox) [bom]
- 'Generating a BOM with all meta-data.' (Bom, Complete) [bom]
```
(Running kibot again immediately without doing anything)
```
seth@seth-[comp name]-5:~/dev/raspi-carrier-pcb$ kibot -e [project name].sch
Using config file: outputs.kibot.yaml
- 'Create the schematic PDF' (Schematic_PDF) [pdf_sch_print]
- 'A PDF of the PCB layers with them all combined.' (PCB_PDF_combined_layers) [pdf_pcb_print]
- 'Generate the gerber files for fab. Per PCBWay' (Gerber files) [gerber]
- 'Create the drill file' (Drill file) [excellon]
Traceback (most recent call last):
  File "/usr/bin/kibot", line 16, in <module>
    main()
  File "/home/seth/.local/lib/python3.8/site-packages/kibot/__main__.py", line 319, in main
    generate_outputs(outputs, args.target, args.invert_sel, args.skip_pre)
  File "/home/seth/.local/lib/python3.8/site-packages/kibot/kiplot.py", line 262, in generate_outputs
    out.run(get_output_dir(out.dir), board)
  File "/home/seth/.local/lib/python3.8/site-packages/kibot/out_base.py", line 55, in run
    self.options.run(output_dir, board)
  File "/home/seth/.local/lib/python3.8/site-packages/kibot/out_any_drill.py", line 106, in run
    os.rename(k_file, file)
FileNotFoundError: [Errno 2] No such file or directory: '/home/seth/dev/[project name]/outputs/gerbers/[project name]-PTH.drl' -> '/home/seth/dev/[project name]/outputs/gerbers/[project name]-PTH_drill.drl'
```

**Comment by set-soft** [comment]
Hi @sethkaz !
Thanks for reporting it. 
The script is assuming you selected separated files for non/plated holes.
Will fix it in some minutes.
