### ISSUE TITLE
GitHub Actions: kicad-git-filters.py: No such file or directory

### ISSUE THREAD

**Issue by TheSlowGrowth** [INTI-CMNB/KiBot#37]
v0.8.1 runs into this error when executing the Docker image:

```
/entrypoint.sh: line 144: /usr/bin/kicad-git-filters.py: No such file or directory
Traceback (most recent call last):
  File "/usr/bin/kibot", line 16, in <module>
    main()
  File "/usr/lib/python3/dist-packages/kibot/__main__.py", line 254, in main
    outputs = cr.read(cf_file)
  File "/usr/lib/python3/dist-packages/kibot/config_reader.py", line 196, in read
    outputs = self._parse_outputs(v)
  File "/usr/lib/python3/dist-packages/kibot/config_reader.py", line 87, in _parse_outputs
    outputs.append(self._parse_output(o))
  File "/usr/lib/python3/dist-packages/kibot/config_reader.py", line 67, in _parse_output
    name_type = "`"+name+"` ("+otype+")"
TypeError: can only concatenate str (not "NoneType") to str
```

This is the GitHub action used:
```
name: Hardware Checks

on:
  push:

jobs:
  KiBot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: INTI-CMNB/KiBot@v0.8.1
      with:
        config: 'test.kibot.yaml'
        schema: 'test.sch'
        board: 'test.kicad_pcb'
        dir: output
    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: output
        path: output

```

**Comment by TheSlowGrowth** [comment]
I was able to resolve the missing kicad-git-filters.py, see here: https://github.com/TheSlowGrowth/KiBot/blob/feature/install-kicad-git-filters/Dockerfile.

I'm still getting the `TypeError: can only concatenate str (not "NoneType") to str` error.

**Comment by TheSlowGrowth** [comment]
The error was ill-formatted KiBot config file (type key is given, but value is empty):

```
[...]
outputs:
  - name: 'Generate schematic PDF'
    comment: "Generate schematic PDF file"
    type: 
    dir: pdf
```

**Comment by set-soft** [comment]
Thanks! The action still experimental.

**Comment by set-soft** [comment]
I also added a catch for the empty type so you get a more descriptive message
