### ISSUE TITLE
[BUG] Nexar API in BOM with KiCost can result in a Silent Error

### ISSUE THREAD

**Issue by fusedFET** [INTI-CMNB/KiBot#433]
Hello,

First things first, great job on this tool. It's a pleasure to use.

**Description**
Having a BOM job with kicost and Nexar as API source, results in an silent error.
This happens when there is a part with a manuf# that is not known by nexar, for example an internal reference.

```txt
Progress:  99%|█████████▉| 83/84 [00:45<00:00,  7.29part/s]
Progress: 100%|██████████| 84/84 [00:45<00:00, 11.07part/s]
Progress: 100%|██████████| 84/84 [00:45<00:00,  1.85part/s]
DEBUG:Distributors solved {'digikey'}, remaining {'arrow', 'farnell', 'tme', 'mouser'} (kibot.kicost.dist - distributor.py:169)
DEBUG:Considering: Mouser ['mouser'] (kibot.kicost.dist - distributor.py:159)
DEBUG:Considering: Element14 ['farnell', 'newark'] (kibot.kicost.dist - distributor.py:159)
DEBUG:Considering: TME ['tme'] (kibot.kicost.dist - distributor.py:159)
DEBUG:Considering: Nexar ['arrow', 'digikey', 'farnell', 'lcsc', 'mouser', 'newark', 'rs', 'tme'] (kibot.kicost.dist - distributor.py:159)
DEBUG:# Getting part data from Nexar ... (kibot.kicost.dist - api_nexar.py:571)
DEBUG:Queries 82 (kibot.kicost.dist - api_nexar.py:613)
DEBUG:Looking in cache /home/temp_user/kicost_cache/Nexar/mpn_unk_THIS_IS_AN_INTERNAL_REFERENCE.dat (kibot.kicost.dist - distributor.py:92)
DEBUG:Found in cache {'hits': 0, 'reference': 'q0', 'parts': []} (kibot.kicost.dist - distributor.py:101)
DEBUG:Data from cache: {'hits': 0, 'parts': [], 'reference': 'q0'} (kibot.kicost.dist - api_nexar.py:548)
Traceback (most recent call last):
  File "/home/temp_user/.local/bin/kibot", line 8, in <module>
    sys.exit(main())
  File "/home/temp_user/.local/lib/python3.8/site-packages/kibot/__main__.py", line 441, in main
    generate_outputs(outputs, args.target, args.invert_sel, args.skip_pre, args.cli_order, args.no_priority,
  File "/home/temp_user/.local/lib/python3.8/site-packages/kibot/kiplot.py", line 522, in generate_outputs
    _generate_outputs(outputs, targets, invert, skip_pre, cli_order, no_priority, dont_stop)
  File "/home/temp_user/.local/lib/python3.8/site-packages/kibot/kiplot.py", line 512, in _generate_outputs
    run_output(out, dont_stop)
  File "/home/temp_user/.local/lib/python3.8/site-packages/kibot/kiplot.py", line 423, in run_output
    out.run(get_output_dir(out.dir, out))
  File "/home/temp_user/.local/lib/python3.8/site-packages/kibot/out_base.py", line 192, in run
    self.options.run(self.expand_filename(output_dir, output))
  File "/home/temp_user/.local/lib/python3.8/site-packages/kibot/out_bom.py", line 936, in run
    do_bom(output, format, comps, self)
  File "/home/temp_user/.local/lib/python3.8/site-packages/kibot/bom/bom.py", line 545, in do_bom
    write_bom(file_name, ext, groups, cfg.columns, cfg)
  File "/home/temp_user/.local/lib/python3.8/site-packages/kibot/bom/bom_writer.py", line 47, in write_bom
    result = write_xlsx(filename, groups, headings, head_names, cfg)
  File "/home/temp_user/.local/lib/python3.8/site-packages/kibot/bom/xlsx_writer.py", line 829, in write_xlsx
    kicost_colors = create_kicost_sheet(workbook, groups, image_data, fmt_title, fmt_info, fmt_subtitle, fmt_head,
  File "/home/temp_user/.local/lib/python3.8/site-packages/kibot/bom/xlsx_writer.py", line 695, in create_kicost_sheet
    return _create_kicost_sheet(workbook, groups, image_data, fmt_title, fmt_info, fmt_subtitle, fmt_head, fmt_cols, cfg)
  File "/home/temp_user/.local/lib/python3.8/site-packages/kibot/bom/xlsx_writer.py", line 652, in _create_kicost_sheet
    query_part_info(parts, dist_list)
  File "/home/temp_user/.local/lib/python3.8/site-packages/kicost/kicost.py", line 78, in query_part_info
    get_dist_parts_info(parts, dist_list, currency)
  File "/home/temp_user/.local/lib/python3.8/site-packages/kicost/distributors/__init__.py", line 50, in get_dist_parts_info
    distributor_class.get_dist_parts_info(parts, dist_list, currency)
  File "/home/temp_user/.local/lib/python3.8/site-packages/kicost/distributors/distributor.py", line 166, in get_dist_parts_info
    solved = api.query_part_info(parts, list(remaining), currency)
  File "/home/temp_user/.local/lib/python3.8/site-packages/kicost/distributors/api_nexar.py", line 624, in query_part_info
    query.remove_manfucturer()
  File "/home/temp_user/.local/lib/python3.8/site-packages/kicost/distributors/api_nexar.py", line 155, in remove_manfucturer
    del self.query['manufacturer']
KeyError: 'manufacturer'
```

Seems like related to the bug fixed in KiCost 1.1.15 -> 1.1.16, but I am not sure.

**To Reproduce**
Running an output job of type 'bom', using kicost and having configured the Nexar API.
the Nexar API 

```yaml
  - name: 'bom_general'
    comment: "Bill of Materials"
    type: bom
    dir: BoM
    options:
      columns:
        - Row
        - field: References
          name: Reference
        - field: Part
          name: Part
        - field: Value
          name: Value
        - field: manf#
          name: Manufacturer P/N
        - field: Footprint
        - field: Description
          name: Description
        - field: 'Quantity Per PCB'
          name: 'Σ PCB'
      group_fields:  ['Value', 'manf#', 'Part']
      normalize_values: true
      normalize_locale: true
      exclude_filter: 'exclude_any'
      distributors:
        - Mouser
        - Digi-Key
        - TME
        - Arrow
        - Farnell
        - Mouser
      xlsx:
        logo: '../assets/xxx.png'
        logo_scale: 1
        datasheet_as_link: 'Datasheet'
        highlight_empty: false
        kicost: true
        specs: true
        kicost_config: kicost_config.yaml
        kicost_api_disable:
          - KitSpace
          - tme
          - LCSC
```

and have a part that is not found by Nexar. Can be a long internal reference for example.

**Expected behavior**
Ignore the part and generate the BOM anyways
Output a warning in the console.

**Environment (please complete the following information):**
- Windows 10, running in WSL.

**Comment by set-soft** [comment]
Hi @fusedFET !
I need a test case for this. Please create a very simple file with this problem.
I tried to reproduce it without success.
