### ISSUE TITLE
[BUG] Lark GrammarError exception when generating BOM

### ISSUE THREAD

**Issue by iank** [INTI-CMNB/KiBot#459]
**Describe the bug**

On Ubuntu 20.04, the kibot package installs python3-lark but does not require a version number, so 0.8.1-1 gets installed, which can't parse `electro.lark` (see traceback below). Manually installing python3-lark 1.1.1-1 from Ubuntu 22.04 resolves the problem.

I understand if you don't support Ubuntu 20.04 in 2023 (I wouldn't), but could I suggest adding a version to the lark dependency in your .deb package? So that the installation will fail early and the problem will clearly present as a dependency issue.

**To Reproduce**

* Install kibot from the set-soft apt repository on Ubuntu 20.04
* See that python3-lark 0.8.1-1 gets installed
* Attempt to generate an HTML or CSV BoM

This doesn't have to do with my project, it's just a failure to load the grammar in kibot/bom/electro_grammar.py:

```
    with open(os.path.join(GS.get_resource_path('parsers'), 'electro.lark'), 'rt') as f:
        g = f.read()
    parser = Lark(g, start='main' , debug=True)
```

Here is my project anyway, though:

* [Repository here](https://github.com/iank/catfood), check out rev 395a4549, run 'make'

**Expected behavior**
BOM generation would complete without error.

**Environment (please complete the following information):**
Where are you running KiBot:
I installed KiBot 1.6.3 using the set-soft repository. I'm on Ubuntu 20.04.

**Additional context**

```
- 'BoM CSV' (generic_bom_csv) [bom]
WARNING:(W009) KiCad config without environment.vars section (kibot - config.py:356)
Traceback (most recent call last):
  File "/usr/bin/kibot", line 33, in <module>
    sys.exit(load_entry_point('kibot==1.6.3', 'console_scripts', 'kibot')())
  File "/usr/lib/python3/dist-packages/kibot/__main__.py", line 520, in main
    generate_outputs(outputs, args.target, args.invert_sel, args.skip_pre, args.cli_order, args.no_priority,
  File "/usr/lib/python3/dist-packages/kibot/kiplot.py", line 527, in generate_outputs
    _generate_outputs(outputs, targets, invert, skip_pre, cli_order, no_priority, dont_stop)
  File "/usr/lib/python3/dist-packages/kibot/kiplot.py", line 517, in _generate_outputs
    run_output(out, dont_stop)
  File "/usr/lib/python3/dist-packages/kibot/kiplot.py", line 418, in run_output
    out.run(get_output_dir(out.dir, out))
  File "/usr/lib/python3/dist-packages/kibot/out_base.py", line 197, in run
    self.options.run(self.expand_filename(output_dir, output))
  File "/usr/lib/python3/dist-packages/kibot/out_bom.py", line 936, in run
    do_bom(output, format, comps, self)
  File "/usr/lib/python3/dist-packages/kibot/bom/bom.py", line 532, in do_bom
    groups = group_components(cfg, comps)
  File "/usr/lib/python3/dist-packages/kibot/bom/bom.py", line 435, in group_components
    c.value_sort = comp_match(c.value, c.ref_prefix, c.ref)
  File "/usr/lib/python3/dist-packages/kibot/bom/units.py", line 217, in comp_match
    result = parse(ref_prefix[0]+' '+with_commas, with_extra=True, stronger=stronger)
  File "/usr/lib/python3/dist-packages/kibot/bom/electro_grammar.py", line 205, in parse
    initialize()
  File "/usr/lib/python3/dist-packages/kibot/bom/electro_grammar.py", line 201, in initialize
    parser = Lark(g, start='main')  # , debug=DEBUG)
  File "/usr/lib/python3/dist-packages/lark/lark.py", line 180, in __init__
    self.terminals, self.rules, self.ignore_tokens = self.grammar.compile(self.options.start)
  File "/usr/lib/python3/dist-packages/lark/load_grammar.py", line 467, in compile
    terminals = [TerminalDef(name, transformer.transform( term_tree ), priority)
  File "/usr/lib/python3/dist-packages/lark/load_grammar.py", line 467, in <listcomp>
    terminals = [TerminalDef(name, transformer.transform( term_tree ), priority)
  File "/usr/lib/python3/dist-packages/lark/visitors.py", line 133, in transform
    tree = t.transform(tree)
  File "/usr/lib/python3/dist-packages/lark/visitors.py", line 79, in transform
    return self._transform_tree(tree)
  File "/usr/lib/python3/dist-packages/lark/visitors.py", line 75, in _transform_tree
    children = list(self._transform_children(tree.children))
  File "/usr/lib/python3/dist-packages/lark/visitors.py", line 66, in _transform_children
    yield self._transform_tree(c)
  File "/usr/lib/python3/dist-packages/lark/visitors.py", line 76, in _transform_tree
    return self._call_userfunc(tree, children)
  File "/usr/lib/python3/dist-packages/lark/visitors.py", line 42, in _call_userfunc
    return f(children)
  File "/usr/lib/python3/dist-packages/lark/load_grammar.py", line 394, in expansion
    raise GrammarError("Lark doesn't support joining terminals with conflicting flags!")
lark.exceptions.GrammarError: Lark doesn't support joining terminals with conflicting flags!
```

**Comment by set-soft** [comment]
Thanks for reporting!
I added (>= 0.10.0) the one used by Debian 11 that I know is enough.
