### ISSUE TITLE
[BUG] Error naming the types of lights in render?

### ISSUE THREAD

**Issue by mundodisco8** [INTI-CMNB/KiBot#505]
**Describe the bug**
I was messing around with the Blender renderer and changed the light type to 'Area' and got this message

```
ERROR:In section 'blender_export_example' (blender_export): Option `type` must be any of ['POINT', ' SUN', ' SPOT', ' HEMI', ' AREA'] not `AREA` (kibot.gs - gs.py:733)
```

Notice the spaces in front of all the options, except POINT. Adding a space to 'AREA' -> ' AREA' stopped the error, but then the render failed. Adding extra verbosity:

```
DEBUG:Executing: /usr/bin/blender -b --factory-startup -P /usr/lib/python3/dist-packages/kibot/blender_scripts/blender_export.py -- --format blender render --output /SnowFlake/Output/Blender_Renders/Snowflake-3D_blender_bottom.blend /SnowFlake/Output/Blender_Renders/Snowflake-3D_blender_bottom.png --scene /tmp/tmpqaivw3h1.json /SnowFlake/Output/Blender_Renders/Snowflake-blender_export.pcb3d (kibot - kiplot.py:157)
DEBUG:- Output from command: Blender 3.5.1 (hash e1ccd9d4a1d3 built 2023-04-24 23:31:15)
Error: Python: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/kibot/blender_scripts/blender_export.py", line 386, in <module>
    main()
  File "/usr/lib/python3/dist-packages/kibot/blender_scripts/blender_export.py", line 364, in main
    c_views = apply_scene(args.scene)
  File "/usr/lib/python3/dist-packages/kibot/blender_scripts/blender_export.py", line 266, in apply_scene
    light_data = bpy.data.lights.new(name, typ)
TypeError: BlendDataLights.new(): error with argument 2, "type" -  enum " AREA" not found in ('POINT', 'SUN', 'SPOT', 'AREA')
Importing PCB3D file ...
skipping solder joint for 'SPDT_SW1_31_2', unsupported shape 'CHAMFERED_RECT'
{
  "camera": {
    "name": "ACamera",
    "position": [
      0.0,
      0.0025,
      0.2
    ],
    "type": "PERSP"
  },
  "lights": [
    {
      "energy": 25,
      "name": "Light A",
      "position": [
        -0.2,
        0.2,
        0.4
      ],
      "type": " AREA"
    }
  ],
  "point_of_view": [
    {
      "rotate_x": -30,
      "rotate_y": 20,
      "rotate_z": 0,
      "view": "Z"
    }
  ],
  "render": {
    "background1": "#66667F",
    "background2": "#CCCCE5",
    "resolution_x": 1280,
    "resolution_y": 720,
    "samples": 1,
    "transparent_background": false
  }
}
- Select all
- Creating camera ACamera at [0.0, 0.0025, 0.2]
- Creating light Light A at [-0.2, 0.2, 0.4], type:  AREA energy: 25

Blender quit
Error: Not freed memory blocks: 21, total unfreed memory 0.002136 MB
 (kibot - kiplot.py:149)
```

**To Reproduce**
I attach a section of my yaml, that should be enough to trigger it on any board

```
  - name: 'blender_export_example'
    comment: 'Exports the PCB in various 3D file formats.'
    type: 'blender_export'
    dir: 'Output/Blender_Renders'
    options:
      # [boolean=true] Add a default light when none specified.
      # The default light is located at (-size*3.33, size*3.33, size*5) where size is max(width, height) of the PCB
      add_default_light: true
      # [dict] Options for the camera.
      # If none specified KiBot will create a suitable camera.
      # If no position is specified for the camera KiBot will look for a suitable position
      camera:
        # [string=''] Name for the camera
        name: 'ACamera'
        # [number|string] X position [m]. You can use `width`, `height` and `size` for PCB dimensions
        pos_x: 0
        # [number|string] Y position [m]. You can use `width`, `height` and `size` for PCB dimensions
        pos_y: 0.0025
        # [number|string] Z position [m]. You can use `width`, `height` and `size` for PCB dimensions
        pos_z: 0.2
        # [string='perspective'] [perspective,orthographic,panoramic] Type of camera
        type: 'perspective'
      # [dict|list(dict)] Options for the light/s
      light:
        # [number=0] How powerful is the light. Using 0 for POINT and SUN KiBot will try to use something useful
        - energy: 25
          # [string=''] Name for the light
          name: 'Light A'
          # [number|string] X position [m]. You can use `width`, `height` and `size` for PCB dimensions
          pos_x: -.2
          # [number|string] Y position [m]. You can use `width`, `height` and `size` for PCB dimensions
          pos_y: .2
          # [number|string] Z position [m]. You can use `width`, `height` and `size` for PCB dimensions
          pos_z: .4
          # [string='POINT'] [POINT, SUN, SPOT, HEMI, AREA] Type of light. SUN lights will illuminate more evenly
          type: ' AREA'
      # [dict|list(dict)] Outputs to generate in the same run
      outputs:
        # [string='%f-%i%I%v.%x'] Name for the generated file (%i='3D_blender_$VIEW' %x=VARIABLE).
        # The extension is selected from the type. Affected by global options
        - output: '%f-%i%I%v.%x'
          # [string='render'] [fbx,obj,x3d,gltf,stl,ply,blender,render] The format for the output.
          # The `render` type will generate a PNG image of the render result.
          # `fbx` is Kaydara's Filmbox, 'obj' is the Wavefront, 'x3d' is the new ISO/IEC standard
          # that replaced VRML, `gltf` is the standardized GL format, `stl` is the 3D printing
          # format, 'ply' is Polygon File Format (Stanford).
          # Note that some formats includes the light and camera and others are just the 3D model
          # (i.e. STL and PLY)
          type: blender
        - output: '%f-%i%I%v.%x'
          type: render
      # [string|dict] Options to export the PCB to Blender.
      # You can also specify the name of the output that generates the PCB3D file.
      # See the `PCB2Blender_2_1` and  `PCB2Blender_2_1_haschtl` templates
      pcb3d:
        # [string|list(string)='_none'] Name of the filter to mark components as not fitted.
        # A short-cut to use for simple cases where a variant is an overkill
        dnf_filter: '_none'
        # [boolean=true] Downloads missing 3D models from KiCad git.
        # Only applies to models in KISYS3DMOD and KICAD6_3DMODEL_DIR.
        # They are downloaded to a temporal directory and discarded.
        # If you want to cache the downloaded files specify a directory using the
        # KIBOT_3D_MODELS environment variable
        download: true
        # [list(string)=[]] List of components to highlight
        highlight: []
        # [boolean=false] Highlight over the component (not under)
        highlight_on_top: false
        # [number=1.5] [0,1000] How much the highlight extends around the component [mm]
        highlight_padding: 1.5
        # [string='https://gitlab.com/kicad/libraries/kicad-packages3D/-/raw/master/'] Base URL for the KiCad 3D models
        kicad_3d_url: 'https://gitlab.com/kicad/libraries/kicad-packages3D/-/raw/master/'
        # [string=''] Text added to the end of the download URL.
        # Can be used to pass variables to the GET request, i.e. ?VAR1=VAL1&VAR2=VAL2
        kicad_3d_url_suffix: ''
        # [boolean=false] Used to exclude 3D models for components with 'virtual' attribute
        no_virtual: false
        # [string='%f-%i%I%v.%x'] Name for the generated PCB3D file (%i='blender_export' %x='pcb3d'). Affected by global options
        output: '%f-%i%I%v.%x'
        # [string|list(string)='_none'] Name of the filter to transform fields before applying other filters.
        # A short-cut to use for simple cases where a variant is an overkill
        pre_transform: '_none'
        # [list(string)|string=all] [none,all] List of components to draw, can be also a string for `none` or `all`.
        # Unlike the `pcbdraw` output, the default is `all`
        show_components: all
        # [boolean=true] Add solder paste only for the populated components.
        # Populated components are the ones listed in `show_components`
        solder_paste_for_populated: true
        # [string=''] Board variant to apply
        variant: ''
        # [string='2.1'] [2.1,2.1_haschtl] Variant of the format used
        version: '2.1'
      # # Options to configure how Blender imports the PCB.
      # # The default values are good for most cases
      # pcb_import:
      # #   # [boolean=true] Center the PCB at the coordinates origin
      #   center: true
      # #   # [boolean=true] Import the components
      #   components: truecat
      # #   # [boolean=true] Separate the sub-PCBs in separated 3D models
      #   cut_boards: true
      # #   # [boolean=true] Create good looking materials
      #   enhance_materials: true
      # #   # [boolean=true] Reuse materials
      #   merge_materials: true
      # #   # [string='SMART'] [NONE,SMART,ALL] The plug-in can add nice looking solder joints.
      # #   # This option controls if we add it for none, all or only for THT/SMD pads with solder paste
      #   solder_joints: 'SMART'
      # #   # [boolean=true] Move the sub-PCBs to their relative position
      #   stack_boards: true
      # #   # [number=1016.0] [508-2032] Texture density in dots per inch
      #   texture_dpi: 1016.0
      # [dict|list(dict)] How the object is viewed by the camera
      point_of_view:
        # [string=''] String to diferentiate the name of this view.
        # When empty we use the `view`
        - file_id: ''
          # [number=0] Angle to rotate the board in the X axis, positive is clockwise [degrees]
          rotate_x: 30
          # [number=0] Angle to rotate the board in the Y axis, positive is clockwise [degrees]
          rotate_y: -20
          # [number=0] Angle to rotate the board in the Z axis, positive is clockwise [degrees]
          rotate_z: 0
          # [string='top'] [top,bottom,front,rear,right,left,z,Z,y,Y,x,X] Point of view.
          # Compatible with `render_3d`
          view: 'bottom'
      # [dict] Controls how the render is done for the `render` output type
      render_options:
        # [boolean=false] When enabled the image will be post-processed to remove the empty space around the image.
        # In this mode the `background2` is changed to be the same as `background1`
        auto_crop: false
        # [string='#66667F'] First color for the background gradient
        background1: '#66667F'
        # [string='#CCCCE5'] Second color for the background gradient
        background2: '#CCCCE5'
        # `height` is an alias for `resolution_y`
        # [number=1280] Width of the image
        resolution_x: 1280
        # [number=720] Height of the image
        resolution_y: 720
        # [number=10] How many samples we create. Each sample is a raytracing render.
        # Use 1 for a raw preview, 10 for a draft and 100 or more for the final render
        samples: 1
        # [boolean=false] Make the background transparent
        transparent_background: false
        # `width` is an alias for `resolution_x`
```

**Environment (please complete the following information):**
- Using a docker image? `kicad7_auto_full:latest`

**Comment by set-soft** [comment]
Thanks for reporting!

The above patch should solve the issue
