### ISSUE TITLE
[BUG] DrawStackupOptions object has no attribute

### ISSUE THREAD

**Issue by N0cynym** [INTI-CMNB/KiBot#631]
**Describe the bug**
Preflight `draw_stackup` causes Kibot failire.

```
Traceback (most recent call last):
  File "/usr/local/bin/kibot", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/kibot/__main__.py", line 568, in main
    generate_outputs(outputs, args.target, args.invert_sel, args.skip_pre, args.cli_order, args.no_priority,
  File "/usr/local/lib/python3.11/dist-packages/kibot/kiplot.py", line 614, in generate_outputs
    _generate_outputs(outputs, targets, invert, skip_pre, cli_order, no_priority, dont_stop)
  File "/usr/local/lib/python3.11/dist-packages/kibot/kiplot.py", line 594, in _generate_outputs
    preflight_checks(skip_pre, targets)
  File "/usr/local/lib/python3.11/dist-packages/kibot/kiplot.py", line 451, in preflight_checks
    BasePreFlight.run_enabled(targets)
  File "/usr/local/lib/python3.11/dist-packages/kibot/pre_base.py", line 145, in run_enabled
    v.apply()
  File "/usr/local/lib/python3.11/dist-packages/kibot/pre_draw_stackup.py", line 446, in apply
    if update_drawing(self._value, self):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/kibot/pre_draw_stackup.py", line 412, in update_drawing
    return update_drawing_group(g, x1, y1, x2-x1, y2-y1, layer, ops.border, gerber_names, ops._columns)
                                                                                          ^^^^^^^^^^^^
AttributeError: 'DrawStackupOptions' object has no attribute '_columns'. Did you mean: 'columns'?
```

**Environment**

- In a CI/CD workflow (`GitLab`)
- [dev_1.7.1-215dad9_k7.0.11_d12.1](https://github.com/inti-cmnb/kicad_auto/pkgs/container/kicad7_auto/231582907?tag=dev_1.7.1-215dad9_k7.0.11_d12.1)

**Comment by set-soft** [comment]
The above patch should fix it.

Thanks for reporting!

Note: Using a "dict" with more options was a workaround
